### ISSUE TITLE
Crashes if WAV file is >= 1hr

### ISSUE THREAD

**Issue by mungewell** [nmichale/audio-mastering#1]
```
C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main>"c:\Program Files\Python37\python.exe" tracks_profiler.py -f "..\..\clips_for_paul\18\18.wav"
Traceback (most recent call last):
  File "tracks_profiler.py", line 75, in <module>
    main()
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "tracks_profiler.py", line 54, in main
    df = run(files, short_target, integrated_target, do_plot)
  File "tracks_profiler.py", line 40, in run
    df.loc[a.file_path] = a.calc_row(short_target=short_target, plot=i if do_plot else None, axes=axes)
  File "C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main\audio_file.py", line 111, in calc_row
    plot=plot, axes=axes)
  File "C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main\audio_file.py", line 46, in max_min_loudness_short_term
    end_time = self.samples_to_time(end)
  File "C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main\audio_file.py", line 81, in samples_to_time
    return datetime.time(minute=int(m), second=int(s), microsecond=int(micro))
ValueError: minute must be in 0..59
```

A shorter version of the input file did process correctly.

**Comment by nmichale** [comment]
Should be fixed now, just needed to add another `divmod` to convert minutes to hours and minutes
