### ISSUE TITLE
'-p' fails on Windows due to missing '/tmp' directory.

### ISSUE THREAD

**Issue by mungewell** [nmichale/audio-mastering#2]
```
C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main>"c:\Program Files\Python37\python.exe" tracks_profiler.py -p -f "..\..\clips_for_paul\18\18_short.wav"
Traceback (most recent call last):
  File "tracks_profiler.py", line 75, in <module>
    main()
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Program Files\Python37\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "tracks_profiler.py", line 54, in main
    df = run(files, short_target, integrated_target, do_plot)
  File "tracks_profiler.py", line 40, in run
    df.loc[a.file_path] = a.calc_row(short_target=short_target, plot=i if do_plot else None, axes=axes)
  File "C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main\audio_file.py", line 111, in calc_row
    plot=plot, axes=axes)
  File "C:\Users\swood\Downloads\audio-mastering-main-20220228\audio-mastering-main\audio_file.py", line 55, in max_min_loudness_short_term
    loudness_df.to_pickle('/tmp/loudness_test.p')
  File "c:\Program Files\Python37\lib\site-packages\pandas\core\generic.py", line 2962, in to_pickle
    storage_options=storage_options,
  File "c:\Program Files\Python37\lib\site-packages\pandas\io\pickle.py", line 99, in to_pickle
    storage_options=storage_options,
  File "c:\Program Files\Python37\lib\site-packages\pandas\io\common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/loudness_test.p'
```

Quick work around is to remove leading `/`. ie

```
        if plot is not None:
            loudness_df.to_pickle('tmp/loudness_test.p')
```

**Comment by nmichale** [comment]
Ah, you know what, that pickling is not even needed. I just removed, should be good now
